#!/usr/bin/env python3
from codafab import *

def main():
    hosts = read_ansible_inventory("../ansible/inventory")
    group = ThreadingGroup(*hosts)
    tar_logs(group)
    copy_back(hosts, 'runlog.tar.gz')

if __name__ == "__main__":
    main()