#!/usr/bin/env python3
from codafab import *

def main():
    hosts = read_ansible_inventory("../ansible/inventory")
    group = ThreadingGroup(*hosts)
    print_summary(status(group))

if __name__ == "__main__":
    main()
