#!/bin/bash

# Bash script to upload testing logs to GC

DATETIME=`date +%Y-%m-%d-%H%M`
DATE=`date +%Y-%m-%d`

read -p "Describe the outcome: " OUTCOME
echo "Proposed Filename: ${DATETIME}-${OUTCOME// /_}.tar.bz2"
read -rsn1 -p"Press any key to begin transfer or CTRL-C to exit." variable;echo

tar -zcvf ${DATETIME}-${OUTCOME// /_}.tar.gz test-*
gsutil cp ${DATETIME}-${OUTCOME// /_}.tar.gz  gs://network-debug/${DATE}/

echo "Stored at gs://network-debug/${DATE}/${DATETIME}-${OUTCOME// /_}.tar.gz"