#!/bin/bash
#set -x

GROUP=$1
COMMAND=$2

# Workaround until we have a better mechanism for figureing out current testnet
if [ -z ${GROUP} ];
    then
        echo "GROUP is unset"

        lastcache=`ls -lot ~/.ansible/tmp/ansible-ec2-*.cache | head -n 1 | awk '{print $8}'`
        echo "Possible GROUP tags:"
        cat ${lastcache} | grep tag_testnet_ | cut -d '"' -f 2
        exit
    else
        echo "GROUP is ${GROUP}"
fi

ansible \
    ${GROUP} \
    -i ec2.py \
    -m shell \
    -a "$COMMAND" \
    -u admin
