#!/bin/bash

# Lazy wrapper: Check for variances of input vs existing files
# eg foo.yaml, foo., foo

playbook=$1

if [ -f $playbook ]; then
    :
elif [ -f ${playbook}yaml ]; then
    playbook+="yaml"
elif [ -f ${playbook}.yaml ]; then
    playbook+=".yaml"
fi

# Workaround until we have a better mechanism for figureing out current testnet
if [ -z ${TESTNET+x} ];
    then
        echo "TESTNET is unset"

        lastcache=`ls -lot ~/.ansible/tmp/ansible-ec2-*.cache | head -n 1 | awk '{print $8}'`
        echo "Possible Values:"
        cat ${lastcache} | grep tag_testnet_ | cut -d '_' -f 3 | cut -d '"' -f 1

        exit
    else
        echo "TESTNET is set to ${TESTNET}"
fi

ansible-playbook \
    --vault-password-file=ansible_vault_password \
    -i ec2.py \
    -e netname=${TESTNET} \
    -e start_time=$(date +%s) \
    ${playbook}
